# Generated by Django 5.0.1 on 2024-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True, help_text='can be left blank', null=True)),
                ('instagram_link', models.URLField(blank=True, help_text='can be left blank', null=True)),
                ('twitter_link', models.URLField(blank=True, help_text='can be left blank', null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='can be left blank', null=True)),
            ],
        ),
    ]
